### ISSUE TITLE
Missing Software License

### ISSUE THREAD

**Issue by rkd-xom** [CamiloTerevinto/TerevintoSoftware.ApiKeys#1]
I'd like to use your software and its nuget packages, but it lacks a license. Would you be able to add one? Preferably MIT License or other OSS? Thanks for this cool project!

**Comment by CamiloTerevinto** [comment]
Hey @rkd-xom, thanks for opening up this issue. I have just pushed an update making explicit the use of the MIT license in this project :)

**Comment by rkd-xom** [comment]
Wow, so fast @CamiloTerevinto  . Many thanks and looking forward to using the project in the real world.
